### ISSUE TITLE
Where is the CSS?

### ISSUE THREAD

**Issue by andrewryan1906** [claudiuconstantin/cron-editor#11]
I've fired this up and it's functional but I can't seem to find the CSS files to make it display properly. I've been digging and the only thing I can find is a reference to bootstrap in the angular.json file, and I've replicated that and it still doesn't display. I fired up a brand new Angular app and tried to display it fresh and no luck... looks like this.

![image](https://user-images.githubusercontent.com/37671394/50190108-e2fd3980-02f5-11e9-8393-b77c99423422.png)

I'm going to continue to look for it but if you could point me in the right direction, that'd be great.

Thanks,
Andrew

**Comment by andrewryan1906** [comment]
OK,

I see the problem... this is Bootstrap 3... I needed to import the older version of Bootstrap.

Thanks,
Andrew

**Comment by claudiuconstantin** [comment]
The best way to avoid these kind of problems is to replace Bootstrap with some custom css. If anybody wants to participate with a PR for this, the entire world would be grateful :)

**Comment by grreeenn** [comment]
@claudiuconstantin I've wrote some basic CSS (SCSS, actually) for it, as I don't want to use bootstrap; does someone need it yet? :)

![image](https://user-images.githubusercontent.com/13204857/61055912-22f34d80-a3fb-11e9-9d58-fe52584a099d.png)

**Comment by en3on** [comment]
@grreeenn Are you able to post the file somewhere? I'd love to use it!

**Comment by shalin-rahman** [comment]
> @claudiuconstantin I've wrote some basic CSS (SCSS, actually) for it, as I don't want to use bootstrap; does someone need it yet? :)
> 
> ![image](https://user-images.githubusercontent.com/13204857/61055912-22f34d80-a3fb-11e9-9d58-fe52584a099d.png)

i need those.

**Comment by aghilimc** [comment]
> @claudiuconstantin I've wrote some basic CSS (SCSS, actually) for it, as I don't want to use bootstrap; does someone need it yet? :)
> 
> ![image](https://user-images.githubusercontent.com/13204857/61055912-22f34d80-a3fb-11e9-9d58-fe52584a099d.png)

i need it, please inform me , where i can find it?

**Comment by maheshyaddanapudi** [comment]
### **CSS**

    .cron-editor-container {
        padding-left: 10px;
      }
      
      .cron-editor-container .cron-editor-radio {
        width: 20px;
        display: inline-block;
      }
      
      .cron-editor-container .cron-editor-select,
      .cron-editor-container .cron-editor-input,
      .cron-editor-container .cron-editor-checkbox {
        display: inline;
      }
      
      .cron-editor-container .well-time-wrapper {
        padding-left: 20px;
      }
      
      .cron-editor-container .inline-block {
        display: inline-block;
      }
      
      .cron-editor-container .minutes,
      .cron-editor-container .hours,
      .cron-editor-container .days,
      .cron-editor-container .seconds {
        width: 70px;
      }
      
      .cron-editor-container .months {
        width: 120px;
      }
      
      .cron-editor-container .month-days {
        width: 130px;
      }
      
      .cron-editor-container .months-small {
        width: 60px;
      }
      
      .cron-editor-container .day-order-in-month {
        width: 95px;
      }
      
      .cron-editor-container .week-days {
        width: 120px;
      }
      
      .cron-editor-container .advanced-cron-editor-input {
        width: 200px;
      }
      
      .cron-editor-container .hour-types {
        width: 70px;
      }
      
      .cron-editor-container .advanced-cron-editor-label {
        font-weight: 200;
      }

      .nav-tabs li {
        height: 50px;
      }

      .nav li a:hover,
        .nav li.active a:focus,
        .nav li.active a:hover{
        background-color:gray;
        }

      .nav li.active a{
            color: #000;
            background-color:cyan;
        }

      .nav-tabs li a {
        border-width: 1px;
        border-color: black;
        border-left-style: solid;
        border-top-style: solid;
        border-right-style: solid;
        border-bottom-style: none;
        cursor: context-menu;
        padding: 27px;
        font-weight: bolder;
        font-display: block;
        font-size: larger;
      }

      .form-control {
        height: auto;
      }

### **HTML**

    <div class="card container-fluid bg-white">
      <div class="mt-5 container-fluid bg-white col-md-8">
        <cron-editor [(cron)]="cronExpression" [disabled]="isCronDisabled" [(options)]="cronOptions"></cron-editor>
        <hr />
        <p>The resulting Cron expression: <strong>{{cronExpression}}</strong></p>
      </div>
    </div>

### **Sample Screenshot**

![Screenshot 2021-04-18 at 2 24 33 AM](https://user-images.githubusercontent.com/24351133/115126522-434b3580-9fed-11eb-9973-0a8c0ece8a28.png)

**Comment by mail4deepali** [comment]
I could not apply these CSS and the tabs are not looking good.
Where to add this CSS?

I have added a component and used cron-editor in it.
Do I need to update the component CSS file or somewhere else I need to add the CSS reference? 
Please help.

Thank you,
Deepali

**Comment by sls-500** [comment]
same Problem as mail4deepali,
included scss and bind it to the html.. cleared bootstrap from dependencies in package.json.. but nothing.. what could block the css in the project ?

Or need to change or add sth in the angular.json?

**Comment by sls-500** [comment]
![Bildschirmfoto 2021-07-30 um 11 22 56](https://user-images.githubusercontent.com/88186608/127632095-76aa904d-a38f-4175-9996-fbab536001e0.png)


it just look like this sadly

**Comment by mail4deepali** [comment]
Hello @sls-500,

Copying the styles to application style.css (src=>style.css) solved the issue.
Hope this helps.
