### ISSUE TITLE
Render not working

### ISSUE THREAD

**Issue by Araknos** [claudiuconstantin/cron-editor#12]
Hello,

I'm looking for a cron (quartz) editor on angular 7, I tried your it looks like: 

<img width="963" alt="croneditor" src="https://user-images.githubusercontent.com/41959778/51666875-fec3c180-1fbe-11e9-8588-7e378067c869.PNG">

What's the problem ? (I have bootstrap)
Thank's.

**Comment by claudiuconstantin** [comment]
You can find a demo [here](https://github.com/claudiuconstantin/cron-editor-sample). How is that working for you?

**Comment by Araknos** [comment]
It's working fine. I absolutely don't know why I don't get this rendering on my project.

**Comment by claudiuconstantin** [comment]
Probably you have some "conflicting" css that is causing the alignment issue

**Comment by Araknos** [comment]
I used same package.json and styles.css. Do you have another idea ? I'll let you know if I solve the problem

**Comment by claudiuconstantin** [comment]
Do you have a repo I can clone? Don't promise I'll have time to look, but I'll try

**Comment by claudiuconstantin** [comment]
I'll close this as there's nothing to do on the library side.

**Comment by Araknos** [comment]
Answering a bit late sorry ! The problem was bootstrap's dependency (cf package.json): `"bootstrap": "^4.2.1"`
I removed it and it's working fine, thank you Claudiu !
