### ISSUE TITLE
Angular 2 cron editor

### ISSUE THREAD

**Issue by bindu1552** [claudiuconstantin/cron-editor#3]
After integrating the changes i'm getting the below error:
] ERROR in c:/NEERCompliance/complianceapp/ComplianceApp.Web/client
-app/app/control-administration/schedule/cron-editor/cron-editor.comp
onent.ts (8,15): Ca

**Comment by claudiuconstantin** [comment]
Please post the entire error log and call stack

**Comment by claudiuconstantin** [comment]
Duplicate of #2, let's continue the discussion there
