### ISSUE TITLE
unix format

### ISSUE THREAD

**Issue by sachingiter** [claudiuconstantin/cron-editor#4]
Thanx for giving us such a good library for cron expression. i am very happy to use it. do you have any plans to create library for unix format??

**Comment by claudiuconstantin** [comment]
What do you exactly mean by „unix format”?

**Comment by claudiuconstantin** [comment]
We're working on an update that will address this... in a way.  We'll make the Cron expression compatible with the not-quite-standard Cron format used by Hangfire 1.7+. As for the standard Unix cron, that would involve major rework. Probably won't be implemented, but I'll investigate it.

The Hangfire Cron format compatibility will be discussed in issue #5. Closing this.
